/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const _dsh_ide_ui_ide_delete_parameter_0$schema = z.string()
const _dsh_ide_ui_ide_delete_result$schema = z.object({
  'ok': z.boolean(),
  'stderr': z.string(),
  'path': z.string(),
})
const _dsh_ide_ui_ide_explore_parameter_0$schema = z.string()
const _dsh_ide_ui_ide_explore_parameter_1$schema = z.union([z.undefined(), z.literal(false), z.literal(true)])
const _dsh_ide_ui_ide_explore_result$schema = z.object({
  'ok': z.boolean(),
  'path': z.string(),
})
const _dsh_ide_ui_ide_gitCommit_parameter_0$schema = z.string()
const _dsh_ide_ui_ide_gitCommit_parameter_1$schema = z.string()
const _dsh_ide_ui_ide_gitCommit_result$schema = z.object({
  'ok': z.boolean(),
  'stdout': z.string(),
  'stderr': z.string(),
})
const _dsh_ide_ui_ide_gitDiff_parameter_0$schema = z.string()
const _dsh_ide_ui_ide_gitDiff_parameter_1$schema = z.union([z.undefined(), z.string()])
const _dsh_ide_ui_ide_gitDiff_result$schema = z.object({
  'stdout': z.string(),
  'ok': z.boolean(),
  'stderr': z.string(),
  'path': z.string(),
})
const _dsh_ide_ui_ide_gitDiscard_parameter_0$schema = z.string()
const _dsh_ide_ui_ide_gitDiscard_parameter_1$schema = z.string()
const _dsh_ide_ui_ide_gitDiscard_parameter_2$schema = z.boolean()
const _dsh_ide_ui_ide_gitDiscard_result$schema = z.object({
  'ok': z.boolean(),
  'stderr': z.string(),
  'path': z.string(),
})
const _dsh_ide_ui_ide_gitStage_parameter_0$schema = z.string()
const _dsh_ide_ui_ide_gitStage_parameter_1$schema = z.array(z.string())
const _dsh_ide_ui_ide_gitStage_result$schema = z.object({
  'ok': z.boolean(),
  'stderr': z.string(),
})
const _dsh_ide_ui_ide_gitStageAll_parameter_0$schema = z.string()
const _dsh_ide_ui_ide_gitStageAll_result$schema = z.object({
  'ok': z.boolean(),
  'stderr': z.string(),
})
const _dsh_ide_ui_ide_gitStatus_parameter_0$schema = z.string()
const _dsh_ide_ui_ide_gitStatus_result$schema = z.object({
  'branch': z.string(),
  'changes': z.array(z.object({
  'xy': z.string(),
  'path': z.string(),
  'renameFrom': z.string(),
  'staged': z.string(),
  'unstaged': z.string(),
})),
  'notRepo': z.boolean(),
  'error': z.string(),
})
const _dsh_ide_ui_ide_gitStatusMap_parameter_0$schema = z.string()
const _dsh_ide_ui_ide_gitStatusMap_result$schema = z.object({
  'branch': z.string(),
  'files': z.record(z.object({
  'code': z.string(),
  'staged': z.boolean(),
})),
  'ignoredDirs': z.array(z.string()),
  'notRepo': z.boolean(),
  'error': z.string(),
})
const _dsh_ide_ui_ide_gitUnstage_parameter_0$schema = z.string()
const _dsh_ide_ui_ide_gitUnstage_parameter_1$schema = z.array(z.string())
const _dsh_ide_ui_ide_gitUnstage_result$schema = z.object({
  'ok': z.boolean(),
  'stderr': z.string(),
})
const _dsh_ide_ui_ide_gitUnstageAll_parameter_0$schema = z.string()
const _dsh_ide_ui_ide_gitUnstageAll_result$schema = z.object({
  'ok': z.boolean(),
  'stderr': z.string(),
})
const _dsh_ide_ui_ide_listDir_parameter_0$schema = z.string()
const _dsh_ide_ui_ide_listDir_result$schema = z.object({
  'path': z.string(),
  'entries': z.array(z.object({
  'name': z.string(),
  'type': z.union([z.literal("directory"), z.literal("file")]),
  'path': z.string(),
  'size': z.union([z.literal(null), z.number()]),
})),
})
const _dsh_ide_ui_ide_mkdir_parameter_0$schema = z.string()
const _dsh_ide_ui_ide_mkdir_result$schema = z.object({
  'ok': z.boolean(),
  'stderr': z.string(),
  'path': z.string(),
})
const _dsh_ide_ui_ide_newFile_parameter_0$schema = z.string()
const _dsh_ide_ui_ide_newFile_result$schema = z.object({
  'ok': z.literal(true),
  'path': z.string(),
})
const _dsh_ide_ui_ide_paste_parameter_0$schema = z.string()
const _dsh_ide_ui_ide_paste_result$schema = z.object({
  'ok': z.boolean(),
  'files': z.array(z.string()),
  'stderr': z.string(),
})
const _dsh_ide_ui_ide_readText_parameter_0$schema = z.string()
const _dsh_ide_ui_ide_readText_result$schema = z.object({
  'path': z.string(),
  'content': z.string(),
  'truncated': z.boolean(),
  'size': z.number(),
})
const _dsh_ide_ui_ide_rename_parameter_0$schema = z.string()
const _dsh_ide_ui_ide_rename_parameter_1$schema = z.string()
const _dsh_ide_ui_ide_rename_result$schema = z.object({
  'ok': z.boolean(),
  'stderr': z.string(),
  'from': z.string(),
  'to': z.string(),
})
const _dsh_ide_ui_ide_roots_result$schema = z.object({
  'root': z.string(),
  'workspaces': z.array(z.object({
  'id': z.string(),
  'title': z.string(),
  'path': z.string(),
})),
})
const _dsh_ide_ui_ide_search_parameter_0$schema = z.string()
const _dsh_ide_ui_ide_search_parameter_1$schema = z.string()
const _dsh_ide_ui_ide_search_parameter_2$schema = z.boolean()
const _dsh_ide_ui_ide_search_result$schema = z.object({
  'error': z.string(),
  'matches': z.array(z.object({
  'path': z.string(),
  'line': z.number(),
  'text': z.string(),
})),
  'files': z.number(),
  'truncated': z.boolean(),
})

export const TYPERT = {
  package: 'dsh-ide-ui',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: 'dsh-ide-ui#ide/delete',
      service: 'ide',
      namespace: 'ide',
      method: 'delete',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'path',
          wire: 'path',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-ide-ui#ide/delete:path',
            schema: _dsh_ide_ui_ide_delete_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-ide-ui#ide/delete:result',
        schema: _dsh_ide_ui_ide_delete_result$schema,
      },
      sourceLocation: {"file":"packages/host/ide/src/index.ts","line":165,"column":9},
    },
    {
      id: 'dsh-ide-ui#ide/explore',
      service: 'ide',
      namespace: 'ide',
      method: 'explore',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'path',
          wire: 'path',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-ide-ui#ide/explore:path',
            schema: _dsh_ide_ui_ide_explore_parameter_0$schema,
          },
        },
        {
          name: 'select',
          wire: 'select',
          source: 'json',
          acceptsUndefined: true,
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-ide-ui#ide/explore:select',
            schema: _dsh_ide_ui_ide_explore_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-ide-ui#ide/explore:result',
        schema: _dsh_ide_ui_ide_explore_result$schema,
      },
      sourceLocation: {"file":"packages/host/ide/src/index.ts","line":177,"column":9},
    },
    {
      id: 'dsh-ide-ui#ide/gitCommit',
      service: 'ide',
      namespace: 'ide',
      method: 'gitCommit',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'cwd',
          wire: 'cwd',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-ide-ui#ide/gitCommit:cwd',
            schema: _dsh_ide_ui_ide_gitCommit_parameter_0$schema,
          },
        },
        {
          name: 'message',
          wire: 'message',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-ide-ui#ide/gitCommit:message',
            schema: _dsh_ide_ui_ide_gitCommit_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-ide-ui#ide/gitCommit:result',
        schema: _dsh_ide_ui_ide_gitCommit_result$schema,
      },
      sourceLocation: {"file":"packages/host/ide/src/index.ts","line":271,"column":9},
    },
    {
      id: 'dsh-ide-ui#ide/gitDiff',
      service: 'ide',
      namespace: 'ide',
      method: 'gitDiff',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'cwd',
          wire: 'cwd',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-ide-ui#ide/gitDiff:cwd',
            schema: _dsh_ide_ui_ide_gitDiff_parameter_0$schema,
          },
        },
        {
          name: 'path',
          wire: 'path',
          source: 'json',
          acceptsUndefined: true,
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-ide-ui#ide/gitDiff:path',
            schema: _dsh_ide_ui_ide_gitDiff_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-ide-ui/types#GitDiffResult',
        schema: _dsh_ide_ui_ide_gitDiff_result$schema,
      },
      sourceLocation: {"file":"packages/host/ide/src/index.ts","line":227,"column":9},
    },
    {
      id: 'dsh-ide-ui#ide/gitDiscard',
      service: 'ide',
      namespace: 'ide',
      method: 'gitDiscard',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'cwd',
          wire: 'cwd',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-ide-ui#ide/gitDiscard:cwd',
            schema: _dsh_ide_ui_ide_gitDiscard_parameter_0$schema,
          },
        },
        {
          name: 'path',
          wire: 'path',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-ide-ui#ide/gitDiscard:path',
            schema: _dsh_ide_ui_ide_gitDiscard_parameter_1$schema,
          },
        },
        {
          name: 'untracked',
          wire: 'untracked',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-ide-ui#ide/gitDiscard:untracked',
            schema: _dsh_ide_ui_ide_gitDiscard_parameter_2$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-ide-ui#ide/gitDiscard:result',
        schema: _dsh_ide_ui_ide_gitDiscard_result$schema,
      },
      sourceLocation: {"file":"packages/host/ide/src/index.ts","line":260,"column":9},
    },
    {
      id: 'dsh-ide-ui#ide/gitStage',
      service: 'ide',
      namespace: 'ide',
      method: 'gitStage',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'cwd',
          wire: 'cwd',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-ide-ui#ide/gitStage:cwd',
            schema: _dsh_ide_ui_ide_gitStage_parameter_0$schema,
          },
        },
        {
          name: 'paths',
          wire: 'paths',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-ide-ui#ide/gitStage:paths',
            schema: _dsh_ide_ui_ide_gitStage_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-ide-ui#ide/gitStage:result',
        schema: _dsh_ide_ui_ide_gitStage_result$schema,
      },
      sourceLocation: {"file":"packages/host/ide/src/index.ts","line":234,"column":9},
    },
    {
      id: 'dsh-ide-ui#ide/gitStageAll',
      service: 'ide',
      namespace: 'ide',
      method: 'gitStageAll',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'cwd',
          wire: 'cwd',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-ide-ui#ide/gitStageAll:cwd',
            schema: _dsh_ide_ui_ide_gitStageAll_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-ide-ui#ide/gitStageAll:result',
        schema: _dsh_ide_ui_ide_gitStageAll_result$schema,
      },
      sourceLocation: {"file":"packages/host/ide/src/index.ts","line":248,"column":9},
    },
    {
      id: 'dsh-ide-ui#ide/gitStatus',
      service: 'ide',
      namespace: 'ide',
      method: 'gitStatus',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'cwd',
          wire: 'cwd',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-ide-ui#ide/gitStatus:cwd',
            schema: _dsh_ide_ui_ide_gitStatus_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-ide-ui/types#GitStatusResult',
        schema: _dsh_ide_ui_ide_gitStatus_result$schema,
      },
      sourceLocation: {"file":"packages/host/ide/src/index.ts","line":191,"column":9},
    },
    {
      id: 'dsh-ide-ui#ide/gitStatusMap',
      service: 'ide',
      namespace: 'ide',
      method: 'gitStatusMap',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'cwd',
          wire: 'cwd',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-ide-ui#ide/gitStatusMap:cwd',
            schema: _dsh_ide_ui_ide_gitStatusMap_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-ide-ui/types#GitStatusMapResult',
        schema: _dsh_ide_ui_ide_gitStatusMap_result$schema,
      },
      sourceLocation: {"file":"packages/host/ide/src/index.ts","line":191,"column":9},
    },
    {
      id: 'dsh-ide-ui#ide/gitUnstage',
      service: 'ide',
      namespace: 'ide',
      method: 'gitUnstage',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'cwd',
          wire: 'cwd',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-ide-ui#ide/gitUnstage:cwd',
            schema: _dsh_ide_ui_ide_gitUnstage_parameter_0$schema,
          },
        },
        {
          name: 'paths',
          wire: 'paths',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-ide-ui#ide/gitUnstage:paths',
            schema: _dsh_ide_ui_ide_gitUnstage_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-ide-ui#ide/gitUnstage:result',
        schema: _dsh_ide_ui_ide_gitUnstage_result$schema,
      },
      sourceLocation: {"file":"packages/host/ide/src/index.ts","line":241,"column":9},
    },
    {
      id: 'dsh-ide-ui#ide/gitUnstageAll',
      service: 'ide',
      namespace: 'ide',
      method: 'gitUnstageAll',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'cwd',
          wire: 'cwd',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-ide-ui#ide/gitUnstageAll:cwd',
            schema: _dsh_ide_ui_ide_gitUnstageAll_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-ide-ui#ide/gitUnstageAll:result',
        schema: _dsh_ide_ui_ide_gitUnstageAll_result$schema,
      },
      sourceLocation: {"file":"packages/host/ide/src/index.ts","line":254,"column":9},
    },
    {
      id: 'dsh-ide-ui#ide/listDir',
      service: 'ide',
      namespace: 'ide',
      method: 'listDir',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'path',
          wire: 'path',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-ide-ui#ide/listDir:path',
            schema: _dsh_ide_ui_ide_listDir_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-ide-ui/types#ListDirResult',
        schema: _dsh_ide_ui_ide_listDir_result$schema,
      },
      sourceLocation: {"file":"packages/host/ide/src/index.ts","line":114,"column":9},
    },
    {
      id: 'dsh-ide-ui#ide/mkdir',
      service: 'ide',
      namespace: 'ide',
      method: 'mkdir',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'path',
          wire: 'path',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-ide-ui#ide/mkdir:path',
            schema: _dsh_ide_ui_ide_mkdir_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-ide-ui#ide/mkdir:result',
        schema: _dsh_ide_ui_ide_mkdir_result$schema,
      },
      sourceLocation: {"file":"packages/host/ide/src/index.ts","line":159,"column":9},
    },
    {
      id: 'dsh-ide-ui#ide/newFile',
      service: 'ide',
      namespace: 'ide',
      method: 'newFile',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'path',
          wire: 'path',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-ide-ui#ide/newFile:path',
            schema: _dsh_ide_ui_ide_newFile_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-ide-ui#ide/newFile:result',
        schema: _dsh_ide_ui_ide_newFile_result$schema,
      },
      sourceLocation: {"file":"packages/host/ide/src/index.ts","line":150,"column":9},
    },
    {
      id: 'dsh-ide-ui#ide/paste',
      service: 'ide',
      namespace: 'ide',
      method: 'paste',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'dest',
          wire: 'dest',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-ide-ui#ide/paste:dest',
            schema: _dsh_ide_ui_ide_paste_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-ide-ui#ide/paste:result',
        schema: _dsh_ide_ui_ide_paste_result$schema,
      },
      sourceLocation: {"file":"packages/host/ide/src/index.ts","line":184,"column":9},
    },
    {
      id: 'dsh-ide-ui#ide/readText',
      service: 'ide',
      namespace: 'ide',
      method: 'readText',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'path',
          wire: 'path',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-ide-ui#ide/readText:path',
            schema: _dsh_ide_ui_ide_readText_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-ide-ui/types#ReadTextResult',
        schema: _dsh_ide_ui_ide_readText_result$schema,
      },
      sourceLocation: {"file":"packages/host/ide/src/index.ts","line":137,"column":9},
    },
    {
      id: 'dsh-ide-ui#ide/rename',
      service: 'ide',
      namespace: 'ide',
      method: 'rename',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'from',
          wire: 'from',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-ide-ui#ide/rename:from',
            schema: _dsh_ide_ui_ide_rename_parameter_0$schema,
          },
        },
        {
          name: 'to',
          wire: 'to',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-ide-ui#ide/rename:to',
            schema: _dsh_ide_ui_ide_rename_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-ide-ui#ide/rename:result',
        schema: _dsh_ide_ui_ide_rename_result$schema,
      },
      sourceLocation: {"file":"packages/host/ide/src/index.ts","line":171,"column":9},
    },
    {
      id: 'dsh-ide-ui#ide/roots',
      service: 'ide',
      namespace: 'ide',
      method: 'roots',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-ide-ui/types#RootsResult',
        schema: _dsh_ide_ui_ide_roots_result$schema,
      },
      sourceLocation: {"file":"packages/host/ide/src/index.ts","line":98,"column":9},
    },
    {
      id: 'dsh-ide-ui#ide/search',
      service: 'ide',
      namespace: 'ide',
      method: 'search',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'cwd',
          wire: 'cwd',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-ide-ui#ide/search:cwd',
            schema: _dsh_ide_ui_ide_search_parameter_0$schema,
          },
        },
        {
          name: 'query',
          wire: 'query',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-ide-ui#ide/search:query',
            schema: _dsh_ide_ui_ide_search_parameter_1$schema,
          },
        },
        {
          name: 'caseSensitive',
          wire: 'caseSensitive',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-ide-ui#ide/search:caseSensitive',
            schema: _dsh_ide_ui_ide_search_parameter_2$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-ide-ui/types#SearchResult',
        schema: _dsh_ide_ui_ide_search_result$schema,
      },
      sourceLocation: {"file":"packages/host/ide/src/index.ts","line":279,"column":9},
    },
  ],
  model: {
    "services": [],
    "events": [],
    "objects": []
  },
}
