/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { GitDiffResult, GitStatusResult, ListDirResult, ReadTextResult, RootsResult, SearchResult } from '@deepseek-ai/dsh-ide/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$696465 {
    delete: (path: string) => Promise<RemoteResult<{ ok: boolean; stderr: string; path: string; }>>
    explore: (path: string, select?: boolean) => Promise<RemoteResult<{ ok: boolean; path: string; }>>
    gitCommit: (cwd: string, message: string) => Promise<RemoteResult<{ ok: boolean; stdout: string; stderr: string; }>>
    gitDiff: (cwd: string, path?: string) => Promise<RemoteResult<GitDiffResult>>
    gitDiscard: (cwd: string, path: string, untracked: boolean) => Promise<RemoteResult<{ ok: boolean; stderr: string; path: string; }>>
    gitStage: (cwd: string, paths: string[]) => Promise<RemoteResult<{ ok: boolean; stderr: string; }>>
    gitStageAll: (cwd: string) => Promise<RemoteResult<{ ok: boolean; stderr: string; }>>
    gitStatus: (cwd: string) => Promise<RemoteResult<GitStatusResult>>
    gitUnstage: (cwd: string, paths: string[]) => Promise<RemoteResult<{ ok: boolean; stderr: string; }>>
    gitUnstageAll: (cwd: string) => Promise<RemoteResult<{ ok: boolean; stderr: string; }>>
    listDir: (path: string) => Promise<RemoteResult<ListDirResult>>
    mkdir: (path: string) => Promise<RemoteResult<{ ok: boolean; stderr: string; path: string; }>>
    newFile: (path: string) => Promise<RemoteResult<{ ok: true; path: string; }>>
    paste: (dest: string) => Promise<RemoteResult<{ ok: boolean; files: string[]; stderr: string; }>>
    readText: (path: string) => Promise<RemoteResult<ReadTextResult>>
    rename: (from: string, to: string) => Promise<RemoteResult<{ ok: boolean; stderr: string; from: string; to: string; }>>
    roots: () => Promise<RemoteResult<RootsResult>>
    search: (cwd: string, query: string, caseSensitive: boolean) => Promise<RemoteResult<SearchResult>>
  }
  interface TypertRemoteMap {
    'ide/delete': (path: string) => Promise<RemoteResult<{ ok: boolean; stderr: string; path: string; }>>
    'ide/explore': (path: string, select?: boolean) => Promise<RemoteResult<{ ok: boolean; path: string; }>>
    'ide/gitCommit': (cwd: string, message: string) => Promise<RemoteResult<{ ok: boolean; stdout: string; stderr: string; }>>
    'ide/gitDiff': (cwd: string, path?: string) => Promise<RemoteResult<GitDiffResult>>
    'ide/gitDiscard': (cwd: string, path: string, untracked: boolean) => Promise<RemoteResult<{ ok: boolean; stderr: string; path: string; }>>
    'ide/gitStage': (cwd: string, paths: string[]) => Promise<RemoteResult<{ ok: boolean; stderr: string; }>>
    'ide/gitStageAll': (cwd: string) => Promise<RemoteResult<{ ok: boolean; stderr: string; }>>
    'ide/gitStatus': (cwd: string) => Promise<RemoteResult<GitStatusResult>>
    'ide/gitUnstage': (cwd: string, paths: string[]) => Promise<RemoteResult<{ ok: boolean; stderr: string; }>>
    'ide/gitUnstageAll': (cwd: string) => Promise<RemoteResult<{ ok: boolean; stderr: string; }>>
    'ide/listDir': (path: string) => Promise<RemoteResult<ListDirResult>>
    'ide/mkdir': (path: string) => Promise<RemoteResult<{ ok: boolean; stderr: string; path: string; }>>
    'ide/newFile': (path: string) => Promise<RemoteResult<{ ok: true; path: string; }>>
    'ide/paste': (dest: string) => Promise<RemoteResult<{ ok: boolean; files: string[]; stderr: string; }>>
    'ide/readText': (path: string) => Promise<RemoteResult<ReadTextResult>>
    'ide/rename': (from: string, to: string) => Promise<RemoteResult<{ ok: boolean; stderr: string; from: string; to: string; }>>
    'ide/roots': () => Promise<RemoteResult<RootsResult>>
    'ide/search': (cwd: string, query: string, caseSensitive: boolean) => Promise<RemoteResult<SearchResult>>
  }
  interface TypertRemoteNamespaceMap {
    'ide': TypertRemoteNamespace$696465
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
